-- 场景模拟：假设我们昨天新招了一个神秘实习生，插入数据时没写年龄：
-- INSERT INTO emp (id, name, job) VALUES (1008, 'Unknown', 'Intern');。
-- 此时他的 age 在数据库里是 NULL。
-- 
-- 灵魂拷问：如果你对这个实习生执行 SELECT age + 10 FROM emp 
-- WHERE name = 'Unknown';，查出来的结果是 10 吗？
-- 
-- ❌ 错误直觉：在 Java 里，没赋值的 Integer 可能会被当成 0（如果是基本数据类型 int），
-- 所以 0 + 10 = 10。
-- 
-- ✅ 底层真相：在 MySQL 的世界里，NULL 代表“未知/不存在”。任何数字与 NULL 进行加减乘除，
-- 结果永远是 NULL！ 这就像你问“一个不知道多少岁的人加上 10 岁是几岁？”，答案只能是“不知道 
-- (NULL)”。